- name: Ensure NFS utilities are installed
  zypper: 
   name: nfs-client
   state: present

- name: Create mountable dir
  file: path=/sapmnt_new state=directory mode=777 owner=root group=root

- name: set mountpoints
  mount: 
   name: /sapmnt_new 
   src: 10.1.0.20:/sapmnt 
   fstype: nfs 
   opts: defaults 
   state: mounted
