- name: create install dir
  file:
    path: /usr/sap/install/kernel
    state: directory

- name: download kernel files
  get_url:
    url: "{{ url_kernel }}"
    dest: /usr/sap/install/kernel/kernel.zip

- name: extract kernel files
  unarchive:
    src: /usr/sap/install/kernel/kernel.zip
    dest: /usr/sap/install/kernel
    remote_src: yes
