---
# This role downloads and extracts SWPM

- name: create install dir
  file:
    path: /usr/sap/install
    state: directory

- name: Download SWPM
  get_url:
    url: "{{ url_swpm }}"
    dest: /usr/sap/install/SWPM.SAR

- name: download sapcar
  get_url:
    url: "{{ url_sapcar }}"
    dest: /usr/sap/install/SAPCAR_LINUX.EXE
    mode: 0755

- name: Extract SWPM
  command: ./SAPCAR_LINUX.EXE -manifest SIGNATURE.SMF -xvf SWPM.SAR -R SWPM
  args:
    chdir: /usr/sap/install
    creates: /usr/sap/install/SWPM
